version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin123
      - DB_PASSWORD=admin123
      - DB_NAME=admin123

  db:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    container_name: database-docker
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
